In [82]:
import pandas as pd
import numpy as np

In [83]:
data=pd.read_csv('/content/drive/MyDrive/datasets/breast-cancer_csv.csv')

In [84]:
data.isna().sum()

age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiat       0
Class          0
dtype: int64

In [85]:
data=data.drop(['breast-quad'],axis=1)

In [86]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['menopause']= label_encoder.fit_transform(data['menopause'])
data['menopause'].unique()

array([2, 0, 1])

In [87]:
data['node-caps']= label_encoder.fit_transform(data['node-caps'])
data['node-caps'].unique()

array([1, 0, 2])

In [88]:
data['breast']= label_encoder.fit_transform(data['breast'])
data['breast'].unique()

array([1, 0])

In [89]:
data['irradiat']= label_encoder.fit_transform(data['irradiat'])
data['irradiat'].unique()

array([0, 1])

In [90]:
data['Class']= label_encoder.fit_transform(data['Class'])
data['Class'].unique()

array([1, 0])

In [91]:
data['age']= label_encoder.fit_transform(data['age'])
data['age'].unique()

array([2, 3, 4, 1, 5, 0])

In [92]:
data['tumor-size']= label_encoder.fit_transform(data['tumor-size'])
data['tumor-size'].unique()

array([ 2,  6,  5,  4,  7,  1,  0,  3,  8, 10,  9])

In [93]:
data.head()

age  menopause  tumor-size inv-nodes  node-caps  deg-malig  breast  \
0    2          2           2       0-2          1          3       1   
1    3          0           2       0-2          0          1       1   
2    3          0           6       0-2          0          2       0   
3    2          2           6       0-2          1          3       1   
4    2          2           5       3-5          1          2       0   

   irradiat  Class  
0         0      1  
1         0      0  
2         0      1  
3         1      0  
4         0      1

In [94]:
data['inv-nodes']= label_encoder.fit_transform(data['inv-nodes'])
data['inv-nodes'].unique()

array([0, 4, 2, 5, 6, 3, 1])

In [95]:
y=data['Class']
x=data.drop(['Class'],axis=1)

In [96]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [97]:

from sklearn import linear_model
lr=linear_model.LogisticRegression()

model=lr.fit(x_train,y_train)

In [98]:
predictions=model.predict(x_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1])

In [99]:
data.head()

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0    2          2           2          0          1          3       1   
1    3          0           2          0          0          1       1   
2    3          0           6          0          0          2       0   
3    2          2           6          0          1          3       1   
4    2          2           5          4          1          2       0   

   irradiat  Class  
0         0      1  
1         0      0  
2         0      1  
3         1      0  
4         0      1

In [108]:
b=x_test.iloc[7]
b

age           3
menopause     0
tumor-size    5
inv-nodes     5
node-caps     1
deg-malig     3
breast        0
irradiat      0
Name: 73, dtype: int64

In [109]:
a=[[3,0,5,5,1,3,0,0]]
pre=model.predict(a)
pre

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])