In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
a=pd.read_csv('D:/afsal/dataset/salaries.csv')

In [3]:
a.head()

work_year experience_level employment_type                  job_title  \
0       2022               MI              FT  Machine Learning Engineer   
1       2022               MI              FT  Machine Learning Engineer   
2       2022               MI              FT             Data Scientist   
3       2022               MI              FT             Data Scientist   
4       2022               MI              FT             Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0  130000             USD         130000                 US             0   
1   90000             USD          90000                 US             0   
2  120000             USD         120000                 US           100   
3  100000             USD         100000                 US           100   
4   85000             USD          85000                 US           100   

  company_location company_size  
0               US            M  
1               US            M  
2               US            M  
3               US            M  
4               US            M

In [4]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332 entries, 0 to 1331
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   work_year           1332 non-null   int64 
 1   experience_level    1332 non-null   object
 2   employment_type     1332 non-null   object
 3   job_title           1332 non-null   object
 4   salary              1332 non-null   int64 
 5   salary_currency     1332 non-null   object
 6   salary_in_usd       1332 non-null   int64 
 7   employee_residence  1332 non-null   object
 8   remote_ratio        1332 non-null   int64 
 9   company_location    1332 non-null   object
 10  company_size        1332 non-null   object
dtypes: int64(4), object(7)
memory usage: 114.6+ KB


In [5]:
a.isna().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [6]:
a.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [7]:
a.experience_level.nunique()


4

In [8]:
a.employment_type.nunique()

4

In [9]:
a.company_location.unique()

array(['US', 'ES', 'GB', 'FR', 'CA', 'MX', 'BR', 'IN', 'AU', 'SG', 'PT',
       'DE', 'NG', 'CZ', 'TR', 'PR', 'FI', 'AS', 'TH', 'NL', 'GR', 'DK',
       'BO', 'PH', 'AL', 'AR', 'BE', 'ID', 'AT', 'EG', 'IT', 'AE', 'IE',
       'LU', 'SI', 'MY', 'EE', 'PL', 'HN', 'CH', 'PK', 'JP', 'DZ', 'RO',
       'IQ', 'RU', 'UA', 'CN', 'HU', 'KE', 'CO', 'NZ', 'IR', 'CL', 'MD',
       'VN', 'HR', 'IL', 'MT'], dtype=object)

In [10]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
a['experience_level']= label_encoder.fit_transform(a['experience_level'])
  
a['experience_level'].unique()

array([2, 3, 1, 0])

In [11]:
a['employment_type']= label_encoder.fit_transform(a['employment_type'])
  
a['employment_type'].unique()

array([2, 3, 0, 1])

In [12]:
a.head()

work_year  experience_level  employment_type                  job_title  \
0       2022                 2                2  Machine Learning Engineer   
1       2022                 2                2  Machine Learning Engineer   
2       2022                 2                2             Data Scientist   
3       2022                 2                2             Data Scientist   
4       2022                 2                2             Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0  130000             USD         130000                 US             0   
1   90000             USD          90000                 US             0   
2  120000             USD         120000                 US           100   
3  100000             USD         100000                 US           100   
4   85000             USD          85000                 US           100   

  company_location company_size  
0               US            M  
1               US            M  
2               US            M  
3               US            M  
4               US            M

In [13]:
a['job_title']= label_encoder.fit_transform(a['job_title'])
  
a['job_title'].unique()

array([47, 30, 21, 38, 15,  6,  2, 61, 24, 45, 20, 25,  0, 52, 28, 54, 60,
       26, 23,  7,  9, 56, 49,  5, 43, 44, 53, 62, 17, 35,  1, 31, 29, 32,
       10,  4, 50, 51, 46, 22, 34, 37, 14, 16, 59, 48,  3, 11, 19, 42, 40,
       27, 39, 13, 55, 18, 58, 57, 41, 33, 12,  8, 63, 36])

In [14]:
a['salary_currency']= label_encoder.fit_transform(a['salary_currency'])
  
a['salary_currency'].unique()

array([17,  8,  9,  2, 11,  0,  6,  1,  7, 15,  5, 14,  3, 12, 10, 13, 16,
        4])

In [15]:
a=a.drop(['employee_residence','company_location'],axis=1)

In [16]:
a['company_size']= label_encoder.fit_transform(a['company_size'])
  
a['company_size'].unique()

array([1, 0, 2])

In [17]:
a.head()

work_year  experience_level  employment_type  job_title  salary  \
0       2022                 2                2         47  130000   
1       2022                 2                2         47   90000   
2       2022                 2                2         30  120000   
3       2022                 2                2         30  100000   
4       2022                 2                2         30   85000   

   salary_currency  salary_in_usd  remote_ratio  company_size  
0               17         130000             0             1  
1               17          90000             0             1  
2               17         120000           100             1  
3               17         100000           100             1  
4               17          85000           100             1

In [18]:
a.columns
y=a['salary_in_usd']
x=a.drop('salary_in_usd',axis=1)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [20]:
from sklearn import linear_model
lr=linear_model.LinearRegression()

model=lr.fit(x_train,y_train)
prediction=model.predict(x_test)

In [21]:
prediction

array([135956.36589006,  91714.27745988, 168793.21152226, 161545.49207328,
       143454.59044598, 143554.29929184, 149192.69870656, 108649.73460448,
       142621.26678734, 161105.8670874 , 154532.69178883, 149153.47267128,
       113057.03510289, 142630.60631955, 143597.48528878, 142596.29910457,
       149251.22644173, 139192.97430028, 129694.74879943, 143535.53305846,
       122436.16071132, 122211.00628528, 118872.79917645, 129750.16335721,
       137520.95040544, 139204.80437441,  72336.34846544, 144866.95110636,
       142636.83267435, 138269.25019621,  78016.03198241,  73253.72791397,
       142636.83267435, 142603.39714905, 161583.5973647 , 156965.35366123,
       121275.88172556, 127099.74173674, 138262.51950667,  59302.14340492,
       143128.76849958, 142621.26678734, 172019.6087106 , 139184.88003903,
       149151.60476484, 111143.03053413, 129959.91332195, 149201.41560329,
       138284.31174849,  57968.2269506 , 141907.78047974,  81484.9551267 ,
       138281.19857108, 1

In [22]:
from sklearn.metrics import mean_squared_error
print('MSC is:',mean_squared_error(y_test,prediction))

MSC is: 3031935834.457652
