In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics

In [2]:

data=pd.read_csv('D:/afsal/dataset/HR_comma_sep.csv')

In [3]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Department', 'salary'],
      dtype='object')

In [5]:
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
data['Department']= label_encoder.fit_transform(data['Department'])
data['Department'].unique()


array([7, 2, 3, 9, 8, 4, 0, 6, 5, 1])

In [6]:
data['salary']= label_encoder.fit_transform(data['salary'])
data['salary'].unique()


array([1, 2, 0])

In [7]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Department  \
0                   3              0     1                      0           7   
1                   6              0     1                      0           7   
2                   4              0     1                      0           7   
3                   5              0     1                      0           7   
4                   3              0     1                      0           7   

   salary  
0       1  
1       2  
2       2  
3       1  
4       1

In [8]:
y=data['salary']
x=data.drop(['salary'],axis=1)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

In [12]:
y_pred

array([1, 1, 2, ..., 1, 2, 1])

In [13]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6162666666666666


In [14]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [15]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5010666666666667


In [17]:
from sklearn import linear_model
lr=linear_model.LogisticRegression()

model=lr.fit(x_train,y_train)

C:\Users\afsal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
predictions=model.predict(x_test)
print(predictions)


[1 2 1 ... 1 2 1]


In [19]:
print("Accuracy:",metrics.accuracy_score(y_test,predictions))

Accuracy: 0.5069333333333333


In [21]:
from sklearn import linear_model
lr=linear_model.LinearRegression()

model=lr.fit(x_train,y_train)

In [22]:
predi=model.predict(x_test)

In [23]:
predi

array([1.36531444, 1.35321354, 1.35035179, ..., 1.3456019 , 1.32992098,
       1.32769318])