In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics

In [2]:
data=pd.read_csv('D:/afsal/dataset/salaries.csv')

In [3]:
data.head()

work_year experience_level employment_type                  job_title  \
0       2022               MI              FT  Machine Learning Engineer   
1       2022               MI              FT  Machine Learning Engineer   
2       2022               MI              FT             Data Scientist   
3       2022               MI              FT             Data Scientist   
4       2022               MI              FT             Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0  130000             USD         130000                 US             0   
1   90000             USD          90000                 US             0   
2  120000             USD         120000                 US           100   
3  100000             USD         100000                 US           100   
4   85000             USD          85000                 US           100   

  company_location company_size  
0               US            M  
1               US            M  
2               US            M  
3               US            M  
4               US            M

In [4]:
data=data.drop(['work_year','employment_type'],axis=1)

In [5]:
data

experience_level                  job_title   salary salary_currency  \
0                  MI  Machine Learning Engineer   130000             USD   
1                  MI  Machine Learning Engineer    90000             USD   
2                  MI             Data Scientist   120000             USD   
3                  MI             Data Scientist   100000             USD   
4                  MI             Data Scientist    85000             USD   
...               ...                        ...      ...             ...   
1327               SE             Data Scientist   412000             USD   
1328               MI   Principal Data Scientist   151000             USD   
1329               EN             Data Scientist   105000             USD   
1330               EN      Business Data Analyst   100000             USD   
1331               SE       Data Science Manager  7000000             INR   

      salary_in_usd employee_residence  remote_ratio company_location  \
0            130000                 US             0               US   
1             90000                 US             0               US   
2            120000                 US           100               US   
3            100000                 US           100               US   
4             85000                 US           100               US   
...             ...                ...           ...              ...   
1327         412000                 US           100               US   
1328         151000                 US           100               US   
1329         105000                 US           100               US   
1330         100000                 US           100               US   
1331          94665                 IN            50               IN   

     company_size  
0               M  
1               M  
2               M  
3               M  
4               M  
...           ...  
1327            L  
1328            L  
1329            S  
1330            L  
1331            L  

[1332 rows x 9 columns]

In [6]:
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
data['salary_currency']= label_encoder.fit_transform(data['salary_currency'])
data['salary_currency'].unique()


array([17,  8,  9,  2, 11,  0,  6,  1,  7, 15,  5, 14,  3, 12, 10, 13, 16,
        4])

In [21]:
data['experience_level']= label_encoder.fit_transform(data['experience_level'])
data['experience_level'].unique()


array([2, 3, 1, 0], dtype=int64)

In [22]:
data['employee_residence']= label_encoder.fit_transform(data['employee_residence'])
data['employee_residence'].unique()


array([62, 22, 25, 24,  9, 12, 43,  8, 33,  3, 52, 16, 45, 15, 14, 60, 11,
       51, 23, 58, 46, 26, 17,  7, 48,  4, 18,  1,  5,  2, 56, 21, 31, 36,
        0, 32, 57, 44, 38, 20, 49, 50, 28, 59, 10, 55, 19, 63, 34, 61,  6,
       30, 37, 54, 39, 13, 47, 35, 53, 27, 41, 40, 29, 42], dtype=int64)

In [23]:
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
data['company_location']= label_encoder.fit_transform(data['company_location'])
data['company_location'].unique()

array([57, 20, 23, 22,  9, 40,  8, 31,  5, 52, 49, 15, 42, 14, 55, 48, 21,
        3, 54, 43, 24, 16,  7, 45,  1,  2,  6, 28,  4, 19, 34,  0, 29, 37,
       53, 41, 18, 47, 25, 10, 46, 35, 17, 50, 32, 51, 56, 12, 27, 36, 13,
       44, 33, 11, 38, 58, 26, 30, 39], dtype=int64)

In [24]:
data.head()

experience_level  job_title  salary  salary_currency  salary_in_usd  \
0                 2         47  130000               17         130000   
1                 2         47   90000               17          90000   
2                 2         30  120000               17         120000   
3                 2         30  100000               17         100000   
4                 2         30   85000               17          85000   

   employee_residence  remote_ratio  company_location  company_size  
0                  62             0                57             1  
1                  62             0                57             1  
2                  62           100                57             1  
3                  62           100                57             1  
4                  62           100                57             1

In [25]:
data['job_title']= label_encoder.fit_transform(data['job_title'])
data['job_title'].unique()

array([47, 30, 21, 38, 15,  6,  2, 61, 24, 45, 20, 25,  0, 52, 28, 54, 60,
       26, 23,  7,  9, 56, 49,  5, 43, 44, 53, 62, 17, 35,  1, 31, 29, 32,
       10,  4, 50, 51, 46, 22, 34, 37, 14, 16, 59, 48,  3, 11, 19, 42, 40,
       27, 39, 13, 55, 18, 58, 57, 41, 33, 12,  8, 63, 36], dtype=int64)

In [26]:
data['company_size']= label_encoder.fit_transform(data['company_size'])
data['company_size'].unique()

array([1, 0, 2], dtype=int64)

In [27]:
data.head()

experience_level  job_title  salary  salary_currency  salary_in_usd  \
0                 2         47  130000               17         130000   
1                 2         47   90000               17          90000   
2                 2         30  120000               17         120000   
3                 2         30  100000               17         100000   
4                 2         30   85000               17          85000   

   employee_residence  remote_ratio  company_location  company_size  
0                  62             0                57             1  
1                  62             0                57             1  
2                  62           100                57             1  
3                  62           100                57             1  
4                  62           100                57             1

In [28]:
y=data['salary']
x=data.drop(['salary'],axis=1)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

In [32]:
y_pred

array([ 160080,  116100,  152000,  210000,  300000,  141300,  144000,
        200000,  160000,  160000,  178800,  207000,   60000,  145000,
         63000,  200000,   38000,  120000,  150000,  170000,  110000,
        144100,   40000,   63000,   62000,   99000,   40000,   63000,
        135000,  126500,   85000,   40000,  135000,  185000,  148800,
        160000,  150000,  113000,  135000,  164000,  180000,  160000,
        195400,  130000,  210000,   83000,  200000,  128000,  100000,
       1000000,  135000,   34000,  106260,  155000,   48000,  110600,
        197000,   65000,  140250,  109280,   60000,  130000,   65000,
        100000,   60000,  179775,  165400,   63000,  175000,  165000,
        225000,   73000,  150000,  180000,  140000,   50000,  168000,
         55000,  250000,   48000,  185900,  224000,  140400,  250000,
         35000,   20000,  115000,   20000,  175000,   60000,   40900,
         60000,  100000,   48000,  164996,  100000,  120000,  197000,
         75000,  159

In [33]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.36936936936936937


In [34]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [35]:
y_pred

array([150000, 100000, 200000, 200000, 200000, 130000, 150000, 191475,
       150000, 150000, 191475, 200000,  50000, 150000,  80000, 200000,
        50000, 100000, 150000, 150000, 100000, 130000,  50000,  50000,
        80000, 100000,  30000,  50000, 130000, 100000, 100000,  50000,
       130000, 191475, 150000, 150000, 150000, 100000, 130000, 100000,
       191475, 150000, 200000, 130000, 200000,  80000, 200000, 130000,
       100000,  30000, 130000,  30000, 100000, 150000,  50000, 100000,
       200000,  50000, 130000, 100000,  50000, 130000,  50000,  80000,
        50000, 191475, 150000,  50000, 191475, 150000, 200000,  50000,
       150000, 191475, 150000,  50000, 150000,  50000, 200000,  50000,
       191475, 150000, 130000, 200000,  30000, 100000, 100000,  30000,
       191475,  80000,  30000,  50000, 100000,  50000, 130000,  50000,
        30000, 200000,  80000, 150000,  50000, 100000, 191475, 100000,
        50000,  80000, 100000, 191475,  80000, 200000, 200000,  80000,
      

In [36]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.15315315315315314


In [37]:
from sklearn import linear_model
lr=linear_model.LogisticRegression()

model=lr.fit(x_train,y_train)

C:\Users\afsal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
predictions=model.predict(x_test)
print(predictions)

[200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 200000 200000 200000 200000 200000 200000 200000 200000 200000 200000
 20000

In [39]:
print("Accuracy:",metrics.accuracy_score(y_test,predictions))

Accuracy: 0.024024024024024024


In [40]:
from sklearn import linear_model
lr=linear_model.LinearRegression()

model=lr.fit(x_train,y_train)

In [41]:
predi=model.predict(x_test)

In [42]:
predi

array([159252.21472633, 129420.2356253 , 232169.92361302, 214945.68272938,
       129907.09892307, 164716.92740258, 175723.36171209, 122532.91273682,
       143885.45743252, 233688.10203763, 201241.55831917, 162028.97433724,
        89392.49674772, 147146.0258551 , 179793.79578862, 135168.87118281,
       196156.25716029, 150344.64813638, 102207.00425395, 158165.35858547,
       209346.16008542, 140994.34028038, 353438.201321  , 121553.04356129,
       261332.9886786 , 154474.70147165, 217718.67543364, 173771.67442365,
       149319.73813682, 132762.87802749, 262470.272228  , 232826.10885225,
       155653.37744948, 137646.90318397, 228248.80189353, 316155.42051392,
       119432.50298366, 195872.24644881, 130413.09505094, 375110.06721239,
       207444.58156789, 143885.45743252, 273259.76827503, 147518.82217014,
       161376.86065272, 243936.60033565, 188913.26463722, 178766.55890651,
       138021.08803697, 266954.17473101, 146168.63095584, 334477.76892791,
       136934.23189611, 1