In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics

In [ ]:
d=pd.read_csv('/content/drive/MyDrive/Social_Network_Ads.csv')

In [ ]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
d['Gender']= label_encoder.fit_transform(d['Gender'])
  
d['Gender'].unique()

array([1, 0])

In [ ]:
data.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
d=d.drop(['User ID'],axis=1)

In [ ]:
d

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [ ]:
y=d['Purchased']
x=d.drop(['Purchased'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size= 0.25,random_state=0)  

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train) 

SVC(random_state=0)

In [ ]:
y_pred=classifier.predict(x_test) 

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
a = [[0, 51, 23000]]

# m= pd.Series(a)

In [ ]:
# type(m)/

In [ ]:
# a=data.index

In [ ]:
y_pred=classifier.predict(a) 

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
y_pred

array([0])

In [ ]:
y_pred

array([0])

iris data set


In [ ]:
data=pd.read_csv('/content/drive/MyDrive/datasets/iris.csv')

In [ ]:
data.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width   Class
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
label_encoder = preprocessing.LabelEncoder()
data['Class']= label_encoder.fit_transform(data['Class'])
  
data['Class'].unique()

array([0, 1, 2])

In [ ]:
data.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [ ]:
y=data['Class']
x=data.drop(['Class'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size= 0.25,random_state=0)  

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train) 

SVC(random_state=0)

In [ ]:
y_pred=classifier.predict(x_test) 

In [ ]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

salary data

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/datasets/Salary_Data.csv')

In [ ]:
data.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
y=data['Salary']
x=data.drop(['Salary'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size= 0.25,random_state=0)  

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train) 

SVC(random_state=0)

In [ ]:
y_pred=classifier.predict(x_test) 

In [ ]:
y_pred

array([ 46205, 121872,  56957,  56957, 105582, 105582, 105582,  56957])

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.0


In [ ]:
print((x_test))

    YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
27              9.6
11              4.0
